GET http://localhost:4005/api/exercises
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFjY291bnQiLCJpZCI6IjYzMjJmYWQ4MTI3MzJlNzA5NGE5MzFjYiIsImlhdCI6MTY2NTE0NTIwM30.NtvlNOrnaN_wuOKuAouw2p10liG2otbIrQojgOxIcI4
Content-Type: application/json

